# Generated by Django 6.0.1 on 2026-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=20)),
                ("firm_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("village", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=15)),
                ("fax_no", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ohe_code", models.CharField(max_length=50)),
                ("rin_no", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("drawing_no", models.CharField(blank=True, max_length=100)),
                (
                    "drawing_image",
                    models.ImageField(blank=True, null=True, upload_to="drawings/"),
                ),
                ("vendors", models.ManyToManyField(to="inventory.vendor")),
            ],
        ),
    ]
